env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
plugins:
  - prettier
rules:
  arrow-parens:
    - warn
    - as-needed
  space-before-function-paren: 0
