language: node_js
node_js:
  - "14"

services:
  - mysql

# 設定參數(Travis CI 會按照參數分別執行)
env:
  - NODE_ENV=travis JWT_SECRET=JWT_SECRET FACEBOOK_APP_ID=501941372136871 FACEBOOK_APP_SECRET=95210c9e1d865d22e91359c68250164c FACEBOOK_CALLBACK=http://localhost:3000/auth/facebook/callback

# 在 install 前執行的指令
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS forum default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g

# 在執行測試之前的指令
before_script:
  - sequelize db:migrate
  - sequelize db:seed:all
