version: '3.7'
services:
  mysql:
    image: mysql:8.0.28-debian
    restart: always
    container_name: mysql-forum-server
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=forum
